version: '3'

services:
  db:
    restart: unless-stopped
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my-network
    env_file:
      - ./backend/src/.env

  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - static_volume:/app/backend/src/staticfiles
      - media_volume:/app/backend/src/media
    entrypoint: /app/docker/backend/entrypoint.sh
    networks:
      - my-network
    depends_on:
      - db
    env_file:
      - ./backend/src/.env

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/prod:/etc/nginx/conf.d
      - static_volume:/app/backend/src/staticfiles
      - media_volume:/app/backend/src/media
    networks:
      - my-network
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  my-network:
