# Generated by Django 4.2.2 on 2023-12-20 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_initial'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResearchPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.DateField()),
                ('is_local', models.BooleanField(default=True)),
                ('student_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.studentresearchsupervision')),
            ],
            options={
                'verbose_name': 'Публикация по итогам НИРС',
                'verbose_name_plural': '4. Публикации по итогам НИРС',
                'ordering': ['publication_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonographPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.DateField()),
                ('is_local', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Публикация монографии',
                'verbose_name_plural': '5. Публикации монографий',
                'ordering': ['name', 'publication_date'],
            },
        ),
    ]
