# Generated by Django 4.2.2 on 2024-02-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('front_link', models.CharField(max_length=100)),
                ('src_model', models.CharField(blank=True, max_length=50, null=True)),
                ('src_field', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Справочник показателей KPI',
                'verbose_name_plural': 'Справочник показателей KPI',
                'ordering': ['id'],
            },
        ),
    ]
