# Generated by Django 4.2.2 on 2023-12-24 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип организационной структуры',
                'verbose_name_plural': 'Типы организационной структуры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.unittype')),
            ],
            options={
                'verbose_name': 'Институт (организационная структура)',
                'verbose_name_plural': 'Список институтов (организационных структур)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('university_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.universityunit')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Список кафедр',
                'ordering': ['name'],
            },
        ),
    ]
