# Generated by Django 4.2.2 on 2023-12-24 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisDefence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('expected_end_date', models.DateField()),
                ('real_end_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'приступил'), (2, 'в процессе'), (3, 'готово'), (4, 'защитил')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Защита диссертации',
                'verbose_name_plural': '1. Защита диссертаций',
                'ordering': ['title', 'expected_end_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentResearchSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('std_first_name', models.CharField(max_length=50)),
                ('std_middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('std_last_name', models.CharField(max_length=100)),
                ('std_fullname', models.CharField(max_length=255)),
                ('group_number', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Руководство НИРС',
                'verbose_name_plural': '3. Руководство НИРС',
                'ordering': ['topic', 'year'],
            },
        ),
        migrations.CreateModel(
            name='StaffMobility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('host_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('activity_type', models.IntegerField(choices=[(1, 'гостевая лекция'), (2, 'стажировка')], default=1)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registers.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мобильность - гостевые лекции и стажировки',
                'verbose_name_plural': '14. Мобильность - гостевые лекции и стажировки',
                'ordering': ['city', 'start_date', 'activity_type'],
            },
        ),
        migrations.CreateModel(
            name='ResearchResultInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('std_research_count', models.SmallIntegerField(blank=True, null=True)),
                ('std_research_pub_count', models.SmallIntegerField(blank=True, null=True)),
                ('conference_count', models.SmallIntegerField(blank=True, null=True)),
                ('mobility_count', models.SmallIntegerField(blank=True, null=True)),
                ('research_project_count', models.SmallIntegerField(blank=True, null=True)),
                ('doctoral_research_count', models.SmallIntegerField(blank=True, null=True)),
                ('monograph_pub_count', models.SmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сводка по НИР',
                'verbose_name_plural': '15. Сводка по НИР',
                'ordering': ['user', 'year'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('real_end_date', models.DateField(blank=True, null=True)),
                ('role_in_project', models.IntegerField(choices=[(1, 'испольнитель'), (5, 'руководитель')], default=1)),
                ('fund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fund_duration', models.SmallIntegerField()),
                ('implementation_results', models.TextField(blank=True, null=True)),
                ('developed_results', models.TextField(blank=True, null=True)),
                ('fund_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registers.fundsource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Научно-исследовательская работа',
                'verbose_name_plural': '12. Научно-исследовательская работы',
                'ordering': ['name', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='InventionPatent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('number', models.CharField(max_length=255)),
                ('issued_date', models.DateField()),
                ('valid_to', models.DateField()),
                ('patent_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_local', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Патент на изобретение',
                'verbose_name_plural': '8 Патенты на изобретение',
                'ordering': ['number', 'issued_date'],
            },
        ),
        migrations.CreateModel(
            name='InventionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('application_date', models.DateField()),
                ('registration_number', models.CharField(max_length=100)),
                ('application_type', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(max_length=255)),
                ('is_local', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на изобретение',
                'verbose_name_plural': '7. Заявки на изобретение',
                'ordering': ['registration_number', 'application_date'],
            },
        ),
        migrations.CreateModel(
            name='DoctoralResearchSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('std_first_name', models.CharField(max_length=50)),
                ('std_middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('std_last_name', models.CharField(max_length=100)),
                ('std_fullname', models.CharField(max_length=255)),
                ('admition_date', models.DateField()),
                ('expected_end_year', models.SmallIntegerField()),
                ('expected_end_month', models.SmallIntegerField()),
                ('real_end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Руководство докторантами и аспирантами',
                'verbose_name_plural': '2. Руководство докторантами и аспирантами',
                'ordering': ['topic', 'admition_date'],
            },
        ),
        migrations.CreateModel(
            name='CopyrightCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('application_date', models.DateField()),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Получение авторских свидетельств',
                'verbose_name_plural': '6. Получение авторских свидетельств',
                'ordering': ['title', 'application_date'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('participation_type', models.IntegerField(choices=[(1, 'доклад'), (2, 'экспонат')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участие в семинарах и конференциях',
                'verbose_name_plural': '13 Участие в семинарах и конференциях',
                'ordering': ['name', 'date'],
            },
        ),
    ]
