# Generated by Django 4.2.2 on 2024-02-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_doctoralresearchsupervision_expected_end_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchresultinfo',
            name='cpw_certificate_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchresultinfo',
            name='invitation_apl_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchresultinfo',
            name='patent_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchresultinfo',
            name='thesis_defence_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
