# Generated by Django 4.2.2 on 2023-11-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_scientificprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='user_name'),
        ),
    ]
