# Generated by Django 4.2.2 on 2023-12-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_scientificprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='updated_ate',
            new_name='updated_at',
        ),
    ]
